import {createHash} from 'node:crypto';
import {mkdir,writeFile,lstat,realpath} from 'node:fs/promises';
import path from 'node:path';
import {Graph,FileNode,validateGraph} from './model.js';
export const escapeHTML=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function sourceLink(graph:Graph,node:FileNode):string {
 const sha=node.revisions.includes('head')?graph.change.headSha:graph.change.analysisBaseSha;
 return graph.repository.url+'/blob/'+sha+'/'+node.path.split('/').map(encodeURIComponent).join('/');
}
export function svg(graph:Graph):string {
 const nodes=graph.nodes.slice(0,80),width=960,height=Math.max(160,nodes.length*66+60),positions=new Map(nodes.map((n,i)=>[n.id,{x:35+(n.roles.includes('changed')?0:n.roles.includes('test')?600:300),y:50+i*66}]));
 const lines=graph.edges.filter(e=>positions.has(e.from)&&positions.has(e.to)).map(e=>{
  const a=positions.get(e.from)!,b=positions.get(e.to)!;const offset=e.revision==='base'?-3:3;
  const sy=a.y+4+offset,ty=b.y+4+offset;
  const d=a.x===b.x?'M'+(a.x+280)+' '+sy+' C'+(a.x+310)+' '+sy+' '+(b.x+310)+' '+ty+' '+(b.x+280)+' '+ty:'M'+(a.x+(a.x<b.x?280:0))+' '+sy+' L'+(b.x+(a.x<b.x?0:280))+' '+ty;
  return '<path d="'+d+'" data-from="'+escapeHTML(e.from)+'" data-to="'+escapeHTML(e.to)+'" stroke="'+(e.revision==='base'?'#7b8b9b':'#a5afff')+'" stroke-width="1.5" fill="none" marker-end="url(#arrow)"/>';
 }).join('');
 const boxes=nodes.map(n=>{const pos=positions.get(n.id)!;return '<g data-node="'+escapeHTML(n.id)+'"><title>'+escapeHTML(n.path+' · '+n.roles.join(', '))+'</title><rect x="'+pos.x+'" y="'+(pos.y-18)+'" width="280" height="44" rx="8" fill="'+(n.roles.includes('changed')?'#273b6d':'#163c39')+'"/><text x="'+(pos.x+12)+'" y="'+pos.y+'" fill="#fff" font-family="system-ui" font-size="12">'+escapeHTML(n.path.length>34?n.path.slice(0,31)+'…':n.path)+'</text></g>';}).join('');
 return '<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Importers point to dependencies. First '+nodes.length+' of '+graph.nodes.length+' files; use the full list for details." viewBox="0 0 '+width+' '+height+'"><defs><marker id="arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#8495aa"/></marker></defs>'+lines+boxes+'</svg>';
}
const style=`*{box-sizing:border-box}body{margin:0;background:#0c1422;color:#e7edf8;font:16px/1.6 system-ui}main{max-width:1100px;margin:auto;padding:32px 20px}header{border-bottom:1px solid #304057;padding-bottom:24px}h1{font-size:clamp(2rem,6vw,3rem);line-height:1.1;margin:8px 0}a{color:#b6caff}button,input,select{font:inherit;border-radius:6px;padding:9px;background:#162337;color:#fff;border:1px solid #73829c}button{cursor:pointer}button:hover{background:#263d60}:focus-visible{outline:3px solid #cfc1ff;outline-offset:3px}label{display:inline-flex;gap:8px;align-items:center;margin:4px 12px 4px 0}.filters{margin:24px 0}.notice{border-left:4px solid #e7b872;background:#292439;padding:12px}li{margin:12px 0;overflow-wrap:anywhere}li button{display:block;max-width:100%;text-align:left}.tag{color:#b0cdbf;font-size:.9rem}pre{white-space:pre-wrap;overflow-wrap:anywhere}summary{cursor:pointer}svg{width:100%;height:auto;max-height:700px}#detail{overflow-wrap:anywhere;border:1px solid #54657b;padding:16px;margin:20px 0}#files{padding-left:22px}[hidden]{display:none!important}@media(max-width:600px){main{padding:20px 14px}.filters label{display:flex}input{max-width:100%}}`;
const script=`const search=document.getElementById('search'),role=document.getElementById('role'),owner=document.getElementById('owner'),files=[...document.querySelectorAll('#files>li')],detail=document.getElementById('detail'),count=document.getElementById('count');function filter(){let visible=0;const visibleIds=new Set();for(const li of files){const show=li.dataset.path.toLowerCase().includes(search.value.toLowerCase())&&(!role.value||li.dataset.roles.split(',').includes(role.value))&&(!owner.value||li.dataset.owners.split(',').includes(owner.value));li.hidden=!show;if(show){visible++;visibleIds.add('file:'+li.dataset.path);}}for(const el of document.querySelectorAll('svg [data-node]'))el.style.display=visibleIds.has(el.dataset.node)?'':'none';for(const el of document.querySelectorAll('svg [data-from]'))el.style.display=visibleIds.has(el.dataset.from)&&visibleIds.has(el.dataset.to)?'':'none';count.textContent=visible+(visible===1?' file shown':' files shown');}for(const el of [search,role,owner])el.addEventListener('input',filter);for(const li of files)li.querySelector('button').addEventListener('click',()=>{detail.replaceChildren();const title=document.createElement('h2');title.textContent=li.dataset.path;detail.append(title);for(const text of [li.dataset.roles,li.dataset.revisions+' revision(s)',li.dataset.owners||'No matched owner',li.dataset.reasons||'No test relationship asserted',li.dataset.relations||'No discovered import relationships']){const p=document.createElement('p');p.textContent=text;detail.append(p);}const a=li.querySelector('a').cloneNode(true);detail.append(a);detail.focus();});filter();`;
const hash=(s:string)=>createHash('sha256').update(s).digest('base64');
export function html(graph:Graph):string {
 validateGraph(graph);
 const owners=[...new Set(graph.nodes.flatMap(n=>n.owners))].sort();
 const relations=(n:FileNode)=>graph.edges.filter(e=>e.from===n.id||e.to===n.id).map(e=>(e.from===n.id?'Imports ':'Imported by ')+(e.from===n.id?e.to:e.from).slice(5)+' ('+e.revision+', '+e.kind+')').join('; ');
 const rows=graph.nodes.map(n=>'<li data-path="'+escapeHTML(n.path)+'" data-roles="'+n.roles.join(',')+'" data-revisions="'+n.revisions.join(',')+'" data-owners="'+escapeHTML(n.owners.join(','))+'" data-relations="'+escapeHTML(relations(n))+'" data-reasons="'+escapeHTML(n.testReasons.join('; '))+'"><button type="button">'+escapeHTML(n.path)+'</button><span class="tag">'+n.roles.join(' · ')+' · '+n.revisions.join('/')+'</span><p>'+escapeHTML(relations(n))+'</p> · <a href="'+escapeHTML(sourceLink(graph,n))+'" rel="noreferrer">Open exact revision</a></li>').join('');
 const warnings=graph.warnings.map(w=>'<li><strong>'+escapeHTML(w.code)+'</strong> '+escapeHTML(w.path??'')+': '+escapeHTML(w.detail)+'</li>').join('');
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src &#39;none&#39;; script-src &#39;sha256-'+hash(script)+'&#39;; style-src &#39;sha256-'+hash(style)+'&#39;; base-uri &#39;none&#39;; form-action &#39;none&#39;; connect-src &#39;none&#39;"><title>PatchRipple · '+escapeHTML(graph.repository.name)+'</title><style>'+style+'</style></head><body><main><header><p>PATCHRIPPLE / STATIC IMPACT MAP</p><h1>See the ripple.</h1><p>'+escapeHTML(graph.repository.name)+' · '+graph.changes.length+' changed paths · '+graph.nodes.length+' candidates</p><p class="notice">'+(graph.completeness.complete?'Complete within supported static syntax.':'Incomplete analysis — review warnings and omissions below.')+' Static candidates are possibilities, not runtime effects, test coverage, or safety proof.</p><details><summary>Revision attribution</summary><pre>Base tip: '+graph.change.baseTipSha+'\nAnalysis base: '+graph.change.analysisBaseSha+'\nHead: '+graph.change.headSha+'\nMode: '+graph.change.mode+'</pre></details></header><section aria-labelledby="map"><h2 id="map">Import neighborhood</h2><p>Arrows point from importers to dependencies. Base edges are gray; head edges are violet. The diagram shows up to 80 nodes; the full candidate list follows.</p>'+svg(graph)+'</section><section aria-labelledby="list"><h2 id="list">Explore files</h2><div class="filters"><label>Find a file <input id="search" type="search"></label><label>Role <select id="role" aria-label="Role"><option value="">All</option><option>changed</option><option>impact</option><option>test</option></select></label><label>Owner <select id="owner" aria-label="Owner"><option value="">All</option>'+owners.map(o=>'<option>'+escapeHTML(o)+'</option>').join('')+'</select></label></div><p id="count" role="status"></p><div id="detail" tabindex="-1" aria-label="Selected file details"><p>Select a file to inspect its roles, revisions, owners, and test evidence.</p></div><ul id="files">'+rows+'</ul></section><section><h2>Warnings and limits</h2><p>'+graph.completeness.omittedNodes+' omitted nodes; '+graph.completeness.omittedEdges+' omitted edges.</p><ul>'+warnings+'</ul><details><summary>All changed paths, including omitted candidates</summary><ul>'+graph.changes.map(c=>'<li>'+c.status+' '+escapeHTML(c.oldPath??c.newPath??'')+(c.status==='R'?' → '+escapeHTML(c.newPath!):'')+'</li>').join('')+'</ul></details></section><footer><p>Generated repo-locally. Output exposes repository paths and ownership. No analysis service, source execution, or network assets.</p></footer></main><script>'+script+'</script></body></html>';
}
export function summary(graph:Graph):string {
 return '## PatchRipple static impact map\n\n'+(graph.completeness.complete?'Complete within supported syntax.':'**Incomplete analysis: inspect warnings.**')+'\n\n'+graph.changes.length+' changes; '+graph.nodes.length+' candidates; '+graph.warnings.length+' warnings. Static candidates are not runtime or safety proof.\n\n<pre>'+escapeHTML(graph.nodes.slice(0,30).map(n=>n.path+' ['+n.roles.join(',')+']').join('\n'))+'</pre>\n\nBase: '+graph.change.analysisBaseSha+'\nHead: '+graph.change.headSha+'\n';
}
async function canonicalTarget(target:string):Promise<string>{
 let parent=path.resolve(target),tail:string[]=[];
 while(true){try{return path.join(await realpath(parent),...tail.reverse());}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;const next=path.dirname(parent);if(next===parent)throw e;tail.push(path.basename(parent));parent=next;}}
}
export async function writeBundle(graph:Graph,out:string,repo:string,generatedAt=new Date().toISOString()):Promise<void>{
 validateGraph(graph);const target=await canonicalTarget(out),root=await realpath(repo);const relative=path.relative(root,target);
 if(relative===''||(!relative.startsWith('..'+path.sep)&&relative!=='..'&&!path.isAbsolute(relative)))throw new Error('Output must be outside analyzed repository');
 try{await lstat(target);throw new Error('Output path already exists; choose a new path');}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}
 await mkdir(target,{recursive:true});
 const outputs={'graph.json':JSON.stringify(graph,null,2)+'\n','index.html':html(graph),'graph.svg':svg(graph),'metadata.json':JSON.stringify({generatedAt,tool:'PatchRipple',version:'0.1.0',completeness:graph.completeness},null,2)+'\n'};
 for(const [name,contents] of Object.entries(outputs))await writeFile(path.join(target,name),contents,{flag:'wx'});
}
