import {createHash} from 'node:crypto';
import path from 'node:path';
import {Graph,FileNode,Revision,compare,validateGraph,warningCategory} from './model.js';
import {viewerStyle} from './viewer-style.js';
import {viewerScript} from './viewer-client.js';
export const escapeHTML=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function sourceLink(graph:Graph,node:FileNode,revision:Revision=node.revisions.includes('head')?'head':'base'):string {
 const sha=revision==='head'?graph.change.headSha:graph.change.analysisBaseSha;
 return graph.repository.url+'/blob/'+sha+'/'+node.path.split('/').map(encodeURIComponent).join('/');
}
const primaryRole=(n:FileNode)=>n.roles.includes('changed')?'changed':n.roles.includes('test')?'test':'impact';
const short=(value:string,max:number)=>value.length>max?value.slice(0,max-1)+'…':value;
export function svg(graph:Graph):string {
 const changed=new Set(graph.nodes.filter(n=>n.roles.includes('changed')).map(n=>n.id));
 const adjacent=new Set(graph.edges.flatMap(e=>changed.has(e.from)?[e.to]:changed.has(e.to)?[e.from]:[]));
 const rank=(n:FileNode)=>changed.has(n.id)?0:adjacent.has(n.id)?1:n.roles.includes('test')?2:3;
  const nodes=[...graph.nodes].sort((a,b)=>rank(a)-rank(b)||compare(a.path,b.path)).slice(0,18),lanes=['changed','impact','test'],counts=[0,0,0];
 const positions=new Map(nodes.map(n=>{const lane=lanes.indexOf(primaryRole(n)),row=counts[lane]++;return [n.id,{x:28+lane*350,y:90+row*84}];}));
 const height=Math.max(250,120+Math.max(...counts)*84);
 const headings=['Changed files','Potential dependents','Related tests'].map((label,i)=>'<text x="'+(28+i*350)+'" y="35" fill="#657487" font-family="Inter,Segoe UI,system-ui,sans-serif" font-size="12">'+label.toUpperCase()+' · '+counts[i]+'</text>').join('');
 const edges=graph.edges.filter(e=>positions.has(e.from)&&positions.has(e.to)).map(e=>{
  const a=positions.get(e.from)!,b=positions.get(e.to)!,offset=e.revision==='base'?-3:3,sx=a.x+(a.x<b.x?300:0),tx=b.x+(a.x<b.x?0:300),sy=a.y+offset,ty=b.y+offset;
  const d=a.x===b.x?'M'+(a.x+300)+' '+sy+' C'+(a.x+335)+' '+sy+' '+(b.x+335)+' '+ty+' '+(b.x+300)+' '+ty:'M'+sx+' '+sy+' C'+((sx+tx)/2)+' '+sy+' '+((sx+tx)/2)+' '+ty+' '+tx+' '+ty;
  return '<path d="'+d+'" data-from="'+escapeHTML(e.from)+'" data-to="'+escapeHTML(e.to)+'" stroke="'+(e.revision==='base'?'#8491a3':'#526b8a')+'" stroke-width="1.4" fill="none" marker-end="url(#arrow)"/>';
 }).join('');
 const boxes=nodes.map(n=>{const p=positions.get(n.id)!,base=path.posix.basename(n.path),dir=path.posix.dirname(n.path);return '<g class="graph-node" data-node="'+escapeHTML(n.id)+'" data-role="'+primaryRole(n)+'" tabindex="0" role="button" aria-label="'+escapeHTML('Inspect '+n.path)+'" aria-pressed="false"><title>'+escapeHTML(n.path+' · '+n.roles.join(', '))+'</title><rect x="'+p.x+'" y="'+(p.y-26)+'" width="300" height="59" rx="8" fill="#f8fafc" stroke="'+(primaryRole(n)==='changed'?'#d1ad60':primaryRole(n)==='test'?'#a9bad1':'#dbe2ea')+'"/><text x="'+(p.x+14)+'" y="'+(p.y-4)+'" fill="#1f2937" font-family="Cascadia Code,Consolas,monospace" font-size="13">'+escapeHTML(short(base,32))+'</text><text x="'+(p.x+14)+'" y="'+(p.y+17)+'" fill="#657487" font-family="Inter,Segoe UI,system-ui,sans-serif" font-size="11">'+escapeHTML(short(dir==='.'?'Repository root':dir,43))+'</text></g>';}).join('');
 return '<svg id="map-svg" xmlns="http://www.w3.org/2000/svg" role="group" aria-label="Importers point to dependencies. '+nodes.length+' of '+graph.nodes.length+' candidates drawn; selecting a file focuses its neighborhood." viewBox="0 0 1080 '+height+'"><defs><marker id="arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#657487"/></marker></defs>'+headings+edges+boxes+'</svg>';
}
const hash=(s:string)=>createHash('sha256').update(s).digest('base64');
export function html(graph:Graph):string {
 validateGraph(graph);
 const owners=[...new Set(graph.nodes.flatMap(n=>n.owners))].sort();
 const groupFor=(filePath:string)=>{const parts=filePath.split('/');return parts.length===1?'Repository root':['packages','apps','services','modules','plugins','libs'].includes(parts[0])&&parts[1]?parts.slice(0,2).join('/'):parts[0];};
 const badge=(role:string)=>'<span class="badge '+role+'">'+role+'</span>';
 const relations=(n:FileNode)=>graph.edges.filter(e=>e.from===n.id||e.to===n.id).map(e=>(e.from===n.id?'Imports ':'Imported by ')+(e.from===n.id?e.to:e.from).slice(5)+' ('+(e.revision==='base'?'base':'head')+', '+e.kind+')');
 const impactPaths=(revision:Revision)=>{
  const reverse=new Map<string,string[]>();for(const edge of graph.edges)if(edge.revision===revision){const list=reverse.get(edge.to)??[];list.push(edge.from);reverse.set(edge.to,list);}
  const paths=new Map<string,string[]>(),queue:string[]=[];for(const n of graph.nodes.filter(n=>n.roles.includes('changed')&&n.revisions.includes(revision)).sort((a,b)=>compare(a.path,b.path))){paths.set(n.id,[n.path]);queue.push(n.id);}
  for(let index=0;index<queue.length;index++){const current=queue[index];for(const dependent of (reverse.get(current)??[]).sort((a,b)=>compare(a,b)))if(!paths.has(dependent)){paths.set(dependent,[...paths.get(current)!,dependent.slice(5)]);queue.push(dependent);}}
  return paths;
 };
 const pathsByRevision={base:impactPaths('base'),head:impactPaths('head')};
 const chains=(n:FileNode)=>({base:pathsByRevision.base.get(n.id),head:pathsByRevision.head.get(n.id)});
 const dependents=(n:FileNode)=>({base:[...pathsByRevision.base].filter(([id,chain])=>id!==n.id&&chain[0]===n.path).map(([id])=>id.slice(5)).sort(compare),head:[...pathsByRevision.head].filter(([id,chain])=>id!==n.id&&chain[0]===n.path).map(([id])=>id.slice(5)).sort(compare)});
 const changeStatus=(n:FileNode)=>{
  const change=graph.changes.find(c=>c.oldPath===n.path||c.newPath===n.path);if(!change)return 'Static candidate';
  if(change.status==='A')return 'Added in head';if(change.status==='D')return 'Removed after base';
  if(change.status==='R')return change.oldPath===n.path?'Renamed to '+change.newPath:'Renamed from '+change.oldPath;
  return change.status==='T'?'File type changed':'Modified in both revisions';
 };
 let previousGroup='';
 const rows=graph.nodes.map(n=>{
  const base=path.posix.basename(n.path),dir=path.posix.dirname(n.path),group=groupFor(n.path),status=changeStatus(n),links=n.revisions.map(revision=>({revision,label:revision==='base'?'Base source ↗':'Head source ↗',href:sourceLink(graph,n,revision)}));
  const heading=group===previousGroup?'':'<li class="file-group-heading" data-package="'+escapeHTML(group)+'" aria-hidden="true">'+escapeHTML(group)+'</li>';previousGroup=group;
  return heading+'<li class="file-row" data-path="'+escapeHTML(n.path)+'" data-package="'+escapeHTML(group)+'" data-roles="'+n.roles.join(',')+'" data-revisions="'+n.revisions.join(',')+'" data-owners="'+escapeHTML(n.owners.join(','))+'" data-change="'+escapeHTML(status)+'" data-relations="'+escapeHTML(JSON.stringify(relations(n)))+'" data-reasons="'+escapeHTML(JSON.stringify(n.testReasons))+'" data-chains="'+escapeHTML(JSON.stringify(chains(n)))+'" data-dependents="'+escapeHTML(JSON.stringify(dependents(n)))+'" data-links="'+escapeHTML(JSON.stringify(links))+'"><div class="file-main"><button type="button" aria-label="'+escapeHTML(n.path)+'" aria-pressed="false"><span class="basename">'+escapeHTML(base)+'</span></button><span class="directory">'+escapeHTML(dir==='.'?'Repository root':dir)+'</span></div><div class="row-meta">'+n.roles.map(badge).join('')+'<span class="badge change-status">'+escapeHTML(status)+'</span><a class="row-link" href="'+escapeHTML(links.at(-1)!.href)+'" aria-label="'+escapeHTML('Open '+(links.at(-1)!.revision==='head'?'head':'base')+' source for '+n.path)+'" rel="noreferrer">'+(links.at(-1)!.revision==='head'?'Head':'Base')+' ↗</a></div></li>';
 }).join('');
 const categoryLabel=(category:string)=>category==='expected-external'?'Expected external exclusion':category==='unresolved-local'?'Unresolved local import':category==='resource-limit'?'Resource limit':'Analysis uncertainty';
 const categories=['unresolved-local','resource-limit','analysis-uncertainty','expected-external'];
 const warningGroups=categories.map(category=>{
  const items=graph.warnings.filter(w=>(w.category??warningCategory(w))===category).sort((a,b)=>compare((a.revision??'')+'|'+(a.path??'')+'|'+a.code,(b.revision??'')+'|'+(b.path??'')+'|'+b.code));
  if(!items.length)return '';
  const severity=category==='expected-external'?'Expected exclusion':'Review required';
  return '<details class="warning-group" data-severity="'+(category==='expected-external'?'expected':'review')+'"'+(category==='expected-external'?'':' open')+'><summary>'+severity+' · '+categoryLabel(category)+' · '+items.length+'</summary><ul>'+items.map(w=>'<li class="warning" tabindex="-1" data-category="'+category+'" data-revision="'+(w.revision??'comparison')+'" data-path="'+escapeHTML(w.path??'')+'"><strong>'+escapeHTML(w.revision==='base'?'Base revision':w.revision==='head'?'Head revision':'Comparison-wide')+' · '+escapeHTML(w.code)+(w.path?' · '+escapeHTML(w.path):'')+'</strong>'+escapeHTML(w.detail)+'</li>').join('')+'</ul></details>';
 }).join('');
 const expected=graph.warnings.filter(w=>(w.category??warningCategory(w))==='expected-external').length,blocking=graph.warnings.length-expected,complete=graph.completeness.complete;
 const stats=[['Changed paths',graph.changes.length,'changed','From the Git comparison'],['Potential dependents',graph.nodes.filter(n=>n.roles.includes('impact')).length,'impact','Static reverse imports'],['Related tests',graph.nodes.filter(n=>n.roles.includes('test')).length,'test','Import and naming evidence']].map(([label,value,role,caption])=>'<div class="stat"><span class="stat-label"><i class="dot '+role+'" aria-hidden="true"></i>'+label+'</span><strong>'+value+'</strong><small>'+caption+'</small></div>').join('')+'<button type="button" class="stat stat-link" id="warning-link"'+(graph.warnings.length?'':' disabled')+'><span class="stat-label"><i class="dot" aria-hidden="true"></i>Analysis warnings</span><strong>'+graph.warnings.length+'</strong><small>'+expected+' expected exclusions · '+blocking+' incompleteness warnings</small></button>';
 const mapData=escapeHTML(JSON.stringify({nodes:graph.nodes,edges:graph.edges}));
 const groupOptions=[...new Set(graph.nodes.map(n=>groupFor(n.path)))].sort(compare).map(group=>'<option>'+escapeHTML(group)+'</option>').join('');
 const graphPanel='<section class="panel graph-panel" aria-labelledby="map"><div class="panel-head"><div><h2 id="map">Import neighborhood</h2><p>Search keeps nearby chain context visible; context nodes are muted.</p></div><span class="pill">'+graph.edges.length+' revision edges</span></div><div class="graph-controls"><label class="field"><span>Revision</span><select id="revision-filter" aria-label="Revision"><option value="both">Base + head</option><option value="base">Base only</option><option value="head">Head only</option></select></label><label class="field"><span>Edge kind</span><select id="edge-filter" aria-label="Edge kind"><option value="all">Runtime + type-only</option><option value="runtime">Runtime imports</option><option value="type-only">Type-only imports</option></select></label><label class="field"><span>Neighborhood depth</span><select id="graph-depth" aria-label="Neighborhood depth"><option value="0">Selected files</option><option value="1">1 hop</option><option value="2" selected>2 hops</option><option value="3">3 hops</option><option value="4">4 hops</option></select></label></div><div class="legend"><span><i class="dot changed" aria-hidden="true"></i>Changed</span><span><i class="dot impact" aria-hidden="true"></i>Dependent</span><span><i class="dot test" aria-hidden="true"></i>Test</span><span><i class="edge-key base" aria-hidden="true"></i>Base dashed</span><span><i class="edge-key" aria-hidden="true"></i>Head solid</span><span><i class="edge-key type-only" aria-hidden="true"></i>Type-only dotted</span></div><div class="graph-scroll"><div id="map-data" hidden data-graph="'+mapData+'"></div>'+(graph.nodes.length?svg(graph):'<p class="graph-empty">No candidate files in this comparison.</p>')+'</div><p class="graph-note" id="graph-note" aria-live="polite">Arrows point from importers to dependencies. The diagram is capped at 18 nodes; the file list retains every candidate.</p></section>';
 const explorer='<section class="panel explorer" id="explorer" aria-labelledby="list"><div class="panel-head"><div><h2 id="list">Explore files</h2><p>Files are grouped by package or top-level directory. The complete candidate list remains available.</p></div><span class="pill">'+graph.nodes.length+' candidates</span></div><div class="filters"><label class="field search-field"><span>Find a file</span><input id="search" type="search" placeholder="Search a path…" autocomplete="off"></label><label class="field"><span>Role</span><select id="role" aria-label="Role"><option value="">All roles</option><option>changed</option><option>impact</option><option>test</option></select></label><label class="field"><span>Owner</span><select id="owner" aria-label="Owner"><option value="">All owners</option>'+owners.map(o=>'<option>'+escapeHTML(o)+'</option>').join('')+'</select></label><label class="field"><span>Package group</span><select id="package-filter" aria-label="Package group"><option value="">All groups</option>'+groupOptions+'</select></label><button type="button" class="reset" id="reset">Clear filters</button></div><div class="list-meta"><p id="count" role="status"></p><span>/ to search</span></div><div class="empty" id="empty" hidden><strong>'+ (graph.nodes.length?'No matching files':'No candidate files')+'</strong><p>'+ (graph.nodes.length?'Try another path, role, owner, or package group.':'The comparison produced no file candidates.')+'</p></div><ul id="files">'+rows+'</ul></section>';
 const inspector='<details class="panel inspector" id="inspector" open><summary class="panel-head"><div><h2>File inspector</h2><p id="inspector-summary">Revision-specific evidence</p></div><span class="pill">Evidence</span></summary><div id="detail" tabindex="-1" aria-label="Selected file details"><p class="detail-help">Select a file to inspect its roles, revisions, owners, and test evidence.</p></div><div class="detail-tip"><button type="button" class="back-to-files" id="back-to-files">Back to files ↑</button><a href="'+escapeHTML(graph.repository.url+'/compare/'+graph.change.analysisBaseSha+'...'+graph.change.headSha)+'" target="_blank" rel="noreferrer">Compare revisions on GitHub ↗</a><span>Source links open the exact analyzed revision.</span></div></details>';
 const audit='<details class="panel audit" id="analysis-details"'+(!complete||graph.warnings.length?' open':'')+'><summary>Warnings &amp; analysis details · '+graph.warnings.length+' warnings</summary><div class="audit-body"><p>'+graph.completeness.omittedNodes+' omitted nodes · '+graph.completeness.omittedEdges+' omitted edges. '+(complete?'Complete within supported static syntax.':'Incomplete analysis — review omissions and warnings.')+'</p><div class="warnings" id="warning-list" tabindex="-1" aria-label="Warnings grouped by severity and category">'+(warningGroups||'<p>No analysis warnings reported.</p>')+'</div><details class="revision-details"><summary>Revision attribution</summary><pre>Base tip: '+graph.change.baseTipSha+'\nAnalysis base: '+graph.change.analysisBaseSha+'\nHead: '+graph.change.headSha+'\nMode: '+graph.change.mode+'</pre></details><details class="revision-details"><summary>All changed paths, including omitted candidates</summary><ul>'+graph.changes.map(c=>'<li>'+c.status+' '+escapeHTML(c.oldPath??c.newPath??'')+(c.status==='R'?' → '+escapeHTML(c.newPath!):'')+'</li>').join('')+'</ul></details></div></details>';
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src &#39;none&#39;; script-src &#39;sha256-'+hash(viewerScript)+'&#39;; style-src &#39;sha256-'+hash(viewerStyle)+'&#39;; base-uri &#39;none&#39;; form-action &#39;none&#39;; connect-src &#39;none&#39;"><title>PatchRipple · '+escapeHTML(graph.repository.name)+'</title><style>'+viewerStyle+'</style></head><body><a class="skip" href="#explorer">Skip to files</a><div class="topbar"><div class="brand"><span class="brand-mark" aria-hidden="true">↳</span>PatchRipple</div><div class="top-meta"><span>Repo-local analysis</span><span class="pill">Offline report</span><span class="status '+(complete?'':'incomplete')+'">'+(complete?'Complete within scope':'Incomplete analysis')+'</span></div></div><main><header class="intro"><div class="intro-copy"><p class="eyebrow">'+escapeHTML(graph.repository.name)+(graph.change.pullRequest?' / PR #'+graph.change.pullRequest:' / Comparison')+'</p><h1>See the ripple.</h1><p>A closer look at changed files, potential dependents, and the evidence connecting them.</p></div><div class="revision"><span>'+ (graph.change.mode==='pr'?'Merge-base comparison':'Direct comparison')+'</span><code>'+graph.change.analysisBaseSha.slice(0,7)+'</code> → <code>'+graph.change.headSha.slice(0,7)+'</code></div></header><section class="stats" aria-label="Comparison summary">'+stats+'</section><div class="workspace"><div class="maincol">'+graphPanel+explorer+'</div>'+inspector+'</div>'+audit+'<div class="scope-note"><span aria-hidden="true">ⓘ</span><p>Static candidates are possibilities, not runtime effects, test coverage, or proof that a change is safe. Review the evidence alongside the diff.</p></div><footer><span>PatchRipple · Built for a closer review.</span><span>Generated repo-locally. No source execution or network assets.</span></footer></main><script>'+viewerScript+'</script></body></html>';
}
