// The offline report only reads its escaped, validated graph payload.
export const viewerScript = `
const search=document.getElementById('search'),role=document.getElementById('role'),owner=document.getElementById('owner'),packageFilter=document.getElementById('package-filter'),reset=document.getElementById('reset'),files=[...document.querySelectorAll('#files>li.file-row')],groupHeadings=[...document.querySelectorAll('#files>.file-group-heading')],detail=document.getElementById('detail'),inspectorSummary=document.getElementById('inspector-summary'),inspector=document.getElementById('inspector'),count=document.getElementById('count'),empty=document.getElementById('empty'),mapSvg=document.getElementById('map-svg'),mapNote=document.getElementById('graph-note'),mapData=document.getElementById('map-data'),revisionFilter=document.getElementById('revision-filter'),edgeFilter=document.getElementById('edge-filter'),depthControl=document.getElementById('graph-depth'),warningLink=document.getElementById('warning-link'),audit=document.getElementById('analysis-details'),backToFiles=document.getElementById('back-to-files'),explorer=document.getElementById('explorer');
const graph=mapData?JSON.parse(mapData.dataset.graph):{nodes:[],edges:[]},byPath=new Map(graph.nodes.map(n=>[n.path,n])),NS='http://www.w3.org/2000/svg',MAX_NODES=18;let selected=null;
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function svgElement(tag,attrs={},text){const node=document.createElementNS(NS,tag);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,String(value));if(text!==undefined)node.textContent=text;return node;}
function section(title,items,fallback,collapsible=false){const s=element('section',undefined,'detail-section');s.append(element('h3',title));if(items.length){const ul=element('ul');for(const item of items)ul.append(element('li',item));if(collapsible){const details=element('details',undefined,'detail-disclosure'),summary=element('summary','Show all '+items.length+' items');details.append(summary,ul);s.append(details);}else s.append(ul);}else s.append(element('p',fallback,'subtle'));detail.append(s);}
function renderMap(){
 if(!mapSvg)return;
 const matches=files.filter(li=>!li.hidden),hasFilters=!!(search.value||role.value||owner.value||packageFilter.value),matchPaths=new Set(hasFilters?matches.map(li=>li.dataset.path):[]);
 const edges=graph.edges.filter(edge=>(revisionFilter.value==='both'||edge.revision===revisionFilter.value)&&(edgeFilter.value==='all'||(edgeFilter.value==='runtime'?edge.kind!=='type-only':edge.kind==='type-only'))),adjacency=new Map();
 for(const edge of edges){const a=edge.from.slice(5),b=edge.to.slice(5);if(!adjacency.has(a))adjacency.set(a,[]);if(!adjacency.has(b))adjacency.set(b,[]);adjacency.get(a).push(b);adjacency.get(b).push(a);}
 const changed=graph.nodes.filter(n=>n.roles.includes('changed')).map(n=>n.path),seeds=hasFilters?[...matchPaths]:[...new Set([...(selected&&!selected.hidden?[selected.dataset.path]:[]),...changed])],distances=new Map(),queue=[];
 for(const filePath of seeds)if(byPath.has(filePath)&&!distances.has(filePath)){distances.set(filePath,0);queue.push(filePath);}
 const maxDepth=Number(depthControl.value||2);for(let i=0;i<queue.length;i++){const current=queue[i],depth=distances.get(current);if(depth>=maxDepth)continue;for(const next of adjacency.get(current)??[])if(!distances.has(next)){distances.set(next,depth+1);queue.push(next);}}
 const rank=node=>matchPaths.has(node.path)?0:node.roles.includes('changed')?1:node.path===selected?.dataset.path?2:3+(distances.get(node.path)??99),chosen=graph.nodes.filter(n=>distances.has(n.path)).sort((a,b)=>rank(a)-rank(b)||distances.get(a.path)-distances.get(b.path)||a.path.localeCompare(b.path)).slice(0,MAX_NODES),ids=new Set(chosen.map(n=>n.id)),visibleEdges=edges.filter(edge=>ids.has(edge.from)&&ids.has(edge.to)),laneCounts=[0,0,0],positions=new Map(chosen.map(n=>{const roleIndex=n.roles.includes('changed')?0:n.roles.includes('test')?2:1,row=laneCounts[roleIndex]++;return[n.id,{x:28+roleIndex*350,y:90+row*84}];})),height=Math.max(250,120+Math.max(...laneCounts)*84);
 mapSvg.replaceChildren();mapSvg.setAttribute('viewBox','0 0 1080 '+height);mapSvg.setAttribute('aria-label',chosen.length?'Focused import neighborhood. '+matches.length+' matching files and '+Math.max(0,chosen.length-matchPaths.size)+' context files shown, capped at '+MAX_NODES+' nodes.':'No files match the current filters.');
 const defs=svgElement('defs'),marker=svgElement('marker',{id:'arrow',viewBox:'0 0 10 10',refX:10,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'});marker.append(svgElement('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#657487'}));defs.append(marker);mapSvg.append(defs);
 for(const [i,label] of ['Changed files','Potential dependents','Related tests'].entries())mapSvg.append(svgElement('text',{x:28+i*350,y:35,fill:'#657487','font-family':'Inter, "Segoe UI", system-ui, sans-serif','font-size':12},label.toUpperCase()+' · '+laneCounts[i]));
 for(const edge of visibleEdges){const a=positions.get(edge.from),b=positions.get(edge.to),offset=edge.revision==='base'?-3:3,sx=a.x+(a.x<b.x?300:0),tx=b.x+(a.x<b.x?0:300),sy=a.y+offset,ty=b.y+offset,d=a.x===b.x?'M'+(a.x+300)+' '+sy+' C'+(a.x+335)+' '+sy+' '+(b.x+335)+' '+ty+' '+(b.x+300)+' '+ty:'M'+sx+' '+sy+' C'+((sx+tx)/2)+' '+sy+' '+((sx+tx)/2)+' '+ty+' '+tx+' '+ty,dash=edge.kind==='type-only'?'1 5':edge.revision==='base'?'8 5':edge.kind==='dynamic-literal'?'4 4':undefined,pathNode=svgElement('path',{class:'graph-edge '+edge.revision+' '+edge.kind,d,'data-from':edge.from,'data-to':edge.to,stroke:edge.revision==='base'?'#8491a3':'#526b8a','stroke-width':edge.kind==='type-only'?1.8:1.4,'stroke-dasharray':dash,fill:'none','marker-end':'url(#arrow)'});pathNode.append(svgElement('title',{},(edge.revision==='base'?'Base':'Head')+' · '+edge.kind+' · '+edge.from.slice(5)+' imports '+edge.to.slice(5)));mapSvg.append(pathNode);}
 for(const n of chosen){const p=positions.get(n.id),base=n.path.split('/').at(-1),dir=n.path.includes('/')?n.path.slice(0,n.path.lastIndexOf('/')):'Repository root',primary=n.roles.includes('changed')?'changed':n.roles.includes('test')?'test':'impact',isMatch=hasFilters&&matchPaths.has(n.path),isSelected=selected?.dataset.path===n.path,g=svgElement('g',{class:'graph-node','data-node':n.id,'data-role':primary,'data-context':String(!isMatch&&!isSelected),'data-search-result':String(isMatch),tabindex:0,role:'button','aria-label':(isMatch?'Search result: ':isSelected?'Selected file: ':'Context for focused file: ')+n.path,'aria-pressed':String(isSelected)});g.append(svgElement('title',{},n.path+' · '+n.roles.join(', ')+(isMatch?' · search/filter result':isSelected?' · selected file':' · nearby context')));g.append(svgElement('rect',{x:p.x,y:p.y-26,width:300,height:59,rx:8,fill:primary==='changed'?'#fff6df':primary==='test'?'#eef3fa':'#f8fafc',stroke:primary==='changed'?'#d1ad60':primary==='test'?'#a9bad1':'#dbe2ea'}));g.append(svgElement('text',{x:p.x+14,y:p.y-4,fill:'#1f2937','font-family':'Cascadia Code, Consolas, monospace','font-size':13},base.length>32?base.slice(0,31)+'…':base));g.append(svgElement('text',{x:p.x+14,y:p.y+17,fill:'#657487','font-family':'Inter, "Segoe UI", system-ui, sans-serif','font-size':11},dir.length>35?dir.slice(0,34)+'…':dir+(isMatch?' · match':isSelected?' · selected':' · context')));mapSvg.append(g);}
 if(mapNote){const context=Math.max(0,chosen.length-[...matchPaths].filter(p=>ids.has('file:'+p)).length-(hasFilters?0:1));mapNote.textContent=chosen.length?'Arrows point from importers to dependencies. '+(hasFilters?'Showing '+Math.min(matches.length,chosen.length)+' matching files':'Focused on '+(selected?.dataset.path??'changed files'))+' with '+context+' nearby context files · '+chosen.length+' of '+graph.nodes.length+' candidates · '+visibleEdges.length+' filtered edges.':'No candidates match the current filters. Clear or adjust filters to explore files.';}
}
function sourceSection(links){const s=element('section',undefined,'detail-section');s.append(element('h3','Exact revision source'));if(links.length){const list=element('div',undefined,'source-links');for(const item of links){const a=element('a',item.label,'source-button');a.href=item.href;a.rel='noreferrer';a.target='_blank';list.append(a);}s.append(list);}else s.append(element('p','No source revision is available for this candidate.','subtle'));detail.append(s);}
function selectFile(li,focus=false){
 selected=li;for(const row of files){row.dataset.selected=String(row===li);row.querySelector('button').setAttribute('aria-pressed',String(row===li));}
 detail.replaceChildren();if(inspectorSummary)inspectorSummary.textContent=li?li.dataset.change+' · '+li.dataset.path:'Revision-specific evidence';
 if(!li){detail.append(element('p','FILE INSPECTOR','eyebrow'),element('h2',files.length?'No matching files':'No changed files'),element('p',files.length?'Clear or adjust your filters to explore the comparison.':'This comparison has no file candidates. Revision and analysis details remain available below.','detail-help'));renderMap();return;}
 detail.append(element('p','SELECTED FILE','eyebrow'),element('h2',li.dataset.path));const badges=element('div',undefined,'detail-badges');for(const r of li.dataset.roles.split(','))badges.append(element('span',r,'badge '+r));badges.append(element('span',li.dataset.change,'badge change-status'));detail.append(badges);
 const revisions=li.dataset.revisions.split(',').filter(Boolean),revisionItems=['Change status: '+li.dataset.change,'Analysis base: '+(revisions.includes('base')?'file is present':'file is absent'), 'Head: '+(revisions.includes('head')?'file is present':'file is absent')];section('Revision evidence',revisionItems,'No revision evidence');sourceSection(JSON.parse(li.dataset.links));
 section('Code owners',li.dataset.owners?li.dataset.owners.split(','):[],'No matched CODEOWNERS rule');section('Related test evidence',JSON.parse(li.dataset.reasons),'No test relationship asserted');
 const chains=JSON.parse(li.dataset.chains),isChanged=li.dataset.roles.split(',').includes('changed');
 if(isChanged){const dependents=JSON.parse(li.dataset.dependents),stats=['Analysis base: '+dependents.base.length+' discovered dependents','Head: '+dependents.head.length+' discovered dependents'];section('Discovered dependents from this changed starting point',stats,'No static reverse-import dependents found');const paths=[...new Set([...dependents.base,...dependents.head])].sort();section('Dependent paths',paths,'No static reverse-import dependents found',true);}
 else {const chainItems=[];for(const revision of ['base','head'])if(chains[revision]?.length>1)chainItems.push((revision==='base'?'Analysis base':'Head')+': '+chains[revision].join(' → '));section('Why this file may be affected',chainItems,'No static reverse-import chain connects this file to a changed path in these revisions');}
 section('Immediate import relationships',JSON.parse(li.dataset.relations),'No discovered import relationships',true);renderMap();
 if(focus){const mobile=window.matchMedia('(max-width: 760px)').matches;if(mobile&&inspector){inspector.open=true;requestAnimationFrame(()=>{detail.focus({preventScroll:true});inspector.scrollIntoView({block:'start'});});}else detail.focus({preventScroll:true});}
}
function filter(){
 let visible=0;for(const li of files){const show=li.dataset.path.toLowerCase().includes(search.value.toLowerCase())&&(!role.value||li.dataset.roles.split(',').includes(role.value))&&(!owner.value||li.dataset.owners.split(',').includes(owner.value))&&(!packageFilter.value||li.dataset.package===packageFilter.value);li.hidden=!show;if(show)visible++;}
 for(const heading of groupHeadings)heading.hidden=!files.some(li=>li.dataset.package===heading.dataset.package&&!li.hidden);
 count.textContent=visible+(visible===1?' file shown':' files shown');empty.hidden=visible>0;reset.disabled=!(search.value||role.value||owner.value||packageFilter.value);
 if(!selected||selected.hidden)selectFile(files.find(li=>!li.hidden&&li.dataset.roles.split(',').includes('changed'))||files.find(li=>!li.hidden)||null);else renderMap();
}
for(const control of [search,role,owner,packageFilter])control.addEventListener('input',filter);
for(const control of [revisionFilter,edgeFilter,depthControl])control.addEventListener('change',renderMap);
reset.addEventListener('click',()=>{search.value='';role.value='';owner.value='';packageFilter.value='';filter();search.focus();});
for(const li of files)li.querySelector('button').addEventListener('click',()=>selectFile(li,true));
if(mapSvg){const inspect=event=>{const group=event.target.closest('[data-node]');if(!group)return;const li=files.find(row=>'file:'+row.dataset.path===group.dataset.node);if(li&&!li.hidden)selectFile(li,true);};mapSvg.addEventListener('click',inspect);mapSvg.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){const group=event.target.closest('[data-node]');if(group){event.preventDefault();inspect(event);}}});}
if(warningLink&&audit)warningLink.addEventListener('click',()=>{audit.open=true;requestAnimationFrame(()=>{const target=document.querySelector('.warning');if(target){target.focus({preventScroll:true});target.scrollIntoView({block:'start'});}});});
if(backToFiles)backToFiles.addEventListener('click',()=>{const target=selected&&!selected.hidden?selected.querySelector('button'):search;if(inspector&&window.matchMedia('(max-width: 760px)').matches)inspector.open=false;explorer.scrollIntoView({block:'start'});if(target){target.focus({preventScroll:true});target.scrollIntoView({block:'center'});}});
document.addEventListener('keydown',event=>{if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&!event.target.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName)){event.preventDefault();search.focus();}});
if(inspector&&window.matchMedia('(max-width: 760px)').matches)inspector.open=false;
filter();selectFile(files.find(li=>li.dataset.roles.split(',').includes('changed'))||files[0]||null);
`;
