// Reads escaped, validated DOM datasets; repository content never becomes executable script.
export const viewerScript = `
const search=document.getElementById('search'),role=document.getElementById('role'),owner=document.getElementById('owner'),reset=document.getElementById('reset'),files=[...document.querySelectorAll('#files>li')],detail=document.getElementById('detail'),count=document.getElementById('count'),empty=document.getElementById('empty'),diagram=[...document.querySelectorAll('#map-svg [data-node]')];
let selected=null;
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function section(title,items,fallback){const s=element('section',undefined,'detail-section');s.append(element('h3',title));if(items.length){const ul=element('ul');for(const item of items)ul.append(element('li',item));s.append(ul);}else s.append(element('p',fallback,'subtle'));detail.append(s);}
function selectFile(li,focus=false){selected=li;for(const row of files){row.dataset.selected=String(row===li);row.querySelector('button').setAttribute('aria-pressed',String(row===li));}for(const node of diagram)node.setAttribute('aria-pressed',String(li&&node.dataset.node==='file:'+li.dataset.path));detail.replaceChildren();if(!li){detail.append(element('p','FILE INSPECTOR','eyebrow'),element('h2',files.length?'No matching files':'No changed files'),element('p',files.length?'Clear or adjust your filters to explore the comparison.':'This comparison has no file candidates. Revision and analysis details remain available below.','detail-help'));return;}detail.append(element('p','SELECTED FILE','eyebrow'),element('h2',li.dataset.path));const badges=element('div',undefined,'detail-badges');for(const r of li.dataset.roles.split(','))badges.append(element('span',r,'badge '+r));detail.append(badges);section('Revision evidence',li.dataset.revisions.split(',').map(r=>r==='head'?'Present in head revision':'Present in analysis-base revision'),'No revision evidence');section('Code owners',li.dataset.owners?li.dataset.owners.split(','):[],'No matched CODEOWNERS rule');section('Related test evidence',JSON.parse(li.dataset.reasons),'No test relationship asserted');section('Import relationships',JSON.parse(li.dataset.relations),'No discovered import relationships');const a=li.querySelector('a').cloneNode(true);a.className='source-button';a.textContent='Open exact revision ↗';detail.append(a);if(focus)detail.focus({preventScroll:window.innerWidth>760});}
function filter(){let visible=0;const ids=new Set();for(const li of files){const show=li.dataset.path.toLowerCase().includes(search.value.toLowerCase())&&(!role.value||li.dataset.roles.split(',').includes(role.value))&&(!owner.value||li.dataset.owners.split(',').includes(owner.value));li.hidden=!show;if(show){visible++;ids.add('file:'+li.dataset.path);}}for(const node of diagram){const show=ids.has(node.dataset.node);node.style.display=show?'':'none';node.setAttribute('tabindex',show?'0':'-1');}for(const edge of document.querySelectorAll('#map-svg [data-from]'))edge.style.display=ids.has(edge.dataset.from)&&ids.has(edge.dataset.to)?'':'none';count.textContent=visible+(visible===1?' file shown':' files shown');empty.hidden=visible>0;reset.disabled=!(search.value||role.value||owner.value);if(!selected||selected.hidden)selectFile(files.find(li=>!li.hidden)||null);}
for(const el of [search,role,owner])el.addEventListener('input',filter);
reset.addEventListener('click',()=>{search.value='';role.value='';owner.value='';filter();search.focus();});
for(const li of files)li.querySelector('button').addEventListener('click',()=>selectFile(li,true));
for(const node of diagram){const inspect=()=>{const li=files.find(row=>'file:'+row.dataset.path===node.dataset.node);if(li&&!li.hidden)selectFile(li,true);};node.addEventListener('click',inspect);node.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();inspect();}});}
document.addEventListener('keydown',event=>{if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&!event.target.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName)){event.preventDefault();search.focus();}});
filter();selectFile(files.find(li=>li.dataset.roles.split(',').includes('changed'))||files[0]||null);
`;
