// The offline report only reads its escaped, validated graph payload.
export const viewerScript = `
const search=document.getElementById('search'),role=document.getElementById('role'),owner=document.getElementById('owner'),reset=document.getElementById('reset'),files=[...document.querySelectorAll('#files>li')],detail=document.getElementById('detail'),count=document.getElementById('count'),empty=document.getElementById('empty'),mapSvg=document.getElementById('map-svg'),mapNote=document.getElementById('graph-note'),mapData=document.getElementById('map-data');
const graph=mapData?JSON.parse(mapData.dataset.graph):{nodes:[],edges:[]},byPath=new Map(graph.nodes.map(n=>[n.path,n])),NS='http://www.w3.org/2000/svg';let selected=null;
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function section(title,items,fallback){const s=element('section',undefined,'detail-section');s.append(element('h3',title));if(items.length){const ul=element('ul');for(const item of items)ul.append(element('li',item));s.append(ul);}else s.append(element('p',fallback,'subtle'));detail.append(s);}
function svgElement(tag,attrs={},text){const node=document.createElementNS(NS,tag);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,String(value));if(text!==undefined)node.textContent=text;return node;}
function renderMap(focusPath){if(!mapSvg)return;const visible=files.filter(li=>!li.hidden),center=visible.find(li=>li.dataset.path===focusPath)||visible.find(li=>li.dataset.roles.split(',').includes('changed'))||visible[0],priority=new Set(),adjacent=new Set();
 if(center){priority.add(center.dataset.path);for(const edge of graph.edges)if(edge.from==='file:'+center.dataset.path||edge.to==='file:'+center.dataset.path)adjacent.add((edge.from==='file:'+center.dataset.path?edge.to:edge.from).slice(5));for(const revision of ['base','head']){const chain=JSON.parse(center.dataset.chains)[revision];if(chain)for(const filePath of chain)priority.add(filePath);}for(const row of visible)if(row.dataset.roles.split(',').includes('test')&&row.dataset.reasons.includes(center.dataset.path))priority.add(row.dataset.path);}
 const changed=new Set(visible.filter(li=>li.dataset.roles.split(',').includes('changed')).map(li=>li.dataset.path));if(!center){for(const filePath of changed)priority.add(filePath);}else for(const filePath of changed)if(priority.size<80)priority.add(filePath);
 const rank=n=>changed.has(n.path)?0:n.path===center?.dataset.path?1:priority.has(n.path)?2:adjacent.has(n.path)?3:n.roles.includes('test')?4:5;
 let chosen=visible.map(li=>byPath.get(li.dataset.path)).filter(Boolean).sort((a,b)=>rank(a)-rank(b)||a.path.localeCompare(b.path)).slice(0,80);if(center&&!chosen.some(n=>n.path===center.dataset.path))chosen=[byPath.get(center.dataset.path),...chosen.slice(0,79)];const ids=new Set(chosen.map(n=>n.id)),lanes=['changed','impact','test'],counts=[0,0,0],positions=new Map(chosen.map(n=>{const lane=lanes.indexOf(n.roles.includes('changed')?'changed':n.roles.includes('test')?'test':'impact'),row=counts[lane]++;return[n.id,{x:28+lane*350,y:90+row*84}];})),height=Math.max(250,120+Math.max(...counts)*84);
 mapSvg.replaceChildren();mapSvg.setAttribute('viewBox','0 0 1080 '+height);mapSvg.setAttribute('aria-label',center?'Importers point to dependencies. Focused on '+center.dataset.path+'; '+chosen.length+' of '+visible.length+' visible candidates drawn.':'No files match the current filters.');const defs=svgElement('defs'),marker=svgElement('marker',{id:'arrow',viewBox:'0 0 10 10',refX:10,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'});marker.append(svgElement('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#a1ada5'}));defs.append(marker);mapSvg.append(defs);
 for(const [i,label] of ['Changed files','Potential dependents','Related tests'].entries())mapSvg.append(svgElement('text',{x:28+i*350,y:35,fill:'#b4c1b7','font-family':'system-ui','font-size':12},label.toUpperCase()+' · '+counts[i]));
 for(const edge of graph.edges.filter(e=>ids.has(e.from)&&ids.has(e.to))){const a=positions.get(edge.from),b=positions.get(edge.to),offset=edge.revision==='base'?-3:3,sx=a.x+(a.x<b.x?300:0),tx=b.x+(a.x<b.x?0:300),sy=a.y+offset,ty=b.y+offset,d=a.x===b.x?'M'+(a.x+300)+' '+sy+' C'+(a.x+335)+' '+sy+' '+(b.x+335)+' '+ty+' '+(b.x+300)+' '+ty:'M'+sx+' '+sy+' C'+((sx+tx)/2)+' '+sy+' '+((sx+tx)/2)+' '+ty+' '+tx+' '+ty;mapSvg.append(svgElement('path',{d,'data-from':edge.from,'data-to':edge.to,stroke:edge.revision==='base'?'#748479':'#a8b8f1','stroke-width':1.4,fill:'none','marker-end':'url(#arrow)'}));}
 for(const n of chosen){const p=positions.get(n.id),base=n.path.split('/').at(-1),dir=n.path.includes('/')?n.path.slice(0,n.path.lastIndexOf('/')):'Repository root',primary=n.roles.includes('changed')?'changed':n.roles.includes('test')?'test':'impact',g=svgElement('g',{class:'graph-node','data-node':n.id,'data-role':primary,tabindex:0,role:'button','aria-label':'Inspect '+n.path,'aria-pressed':String(selected?.dataset.path===n.path)});g.append(svgElement('title',{},n.path+' · '+n.roles.join(', ')));g.append(svgElement('rect',{x:p.x,y:p.y-26,width:300,height:59,rx:8,fill:'#202823',stroke:primary==='changed'?'#8d7245':primary==='test'?'#58708d':'#435347'}));g.append(svgElement('text',{x:p.x+14,y:p.y-4,fill:'#eff4ef','font-family':'ui-monospace,monospace','font-size':13},base.length>32?base.slice(0,31)+'…':base));g.append(svgElement('text',{x:p.x+14,y:p.y+17,fill:'#a1ada5','font-family':'system-ui','font-size':11},dir.length>43?dir.slice(0,42)+'…':dir));mapSvg.append(g);}
 if(mapNote)mapNote.textContent=center?'Arrows point from importers to dependencies. Focused on '+center.dataset.path+' · '+chosen.length+' of '+visible.length+' visible candidates. Select another file to recenter.':'No matching files are visible in the map. Clear or adjust filters to explore candidates.';
}
function selectFile(li,focus=false){selected=li;for(const row of files){row.dataset.selected=String(row===li);row.querySelector('button').setAttribute('aria-pressed',String(row===li));}detail.replaceChildren();if(!li){detail.append(element('p','FILE INSPECTOR','eyebrow'),element('h2',files.length?'No matching files':'No changed files'),element('p',files.length?'Clear or adjust your filters to explore the comparison.':'This comparison has no file candidates. Revision and analysis details remain available below.','detail-help'));renderMap(null);return;}detail.append(element('p','SELECTED FILE','eyebrow'),element('h2',li.dataset.path));const badges=element('div',undefined,'detail-badges');for(const r of li.dataset.roles.split(','))badges.append(element('span',r,'badge '+r));detail.append(badges);section('Revision evidence',li.dataset.revisions.split(',').map(r=>r==='head'?'Present in head revision':'Present in analysis-base revision'),'No revision evidence');section('Code owners',li.dataset.owners?li.dataset.owners.split(','):[],'No matched CODEOWNERS rule');section('Related test evidence',JSON.parse(li.dataset.reasons),'No test relationship asserted');const chains=JSON.parse(li.dataset.chains),chainItems=[];for(const revision of ['base','head'])if(chains[revision]?.length>1)chainItems.push((revision==='base'?'Analysis base':'Head')+': '+chains[revision].join(' → '));section('Why this file may be affected',chainItems,'No static reverse-import chain connects this file to a changed path in these revisions');section('Immediate import relationships',JSON.parse(li.dataset.relations),'No discovered import relationships');const a=li.querySelector('a').cloneNode(true);a.className='source-button';a.textContent='Open exact revision ↗';detail.append(a);renderMap(li.dataset.path);if(focus)detail.focus({preventScroll:window.innerWidth>760});}
function filter(){let visible=0;for(const li of files){const show=li.dataset.path.toLowerCase().includes(search.value.toLowerCase())&&(!role.value||li.dataset.roles.split(',').includes(role.value))&&(!owner.value||li.dataset.owners.split(',').includes(owner.value));li.hidden=!show;if(show)visible++;}count.textContent=visible+(visible===1?' file shown':' files shown');empty.hidden=visible>0;reset.disabled=!(search.value||role.value||owner.value);if(!selected||selected.hidden)selectFile(files.find(li=>!li.hidden)||null);else renderMap(selected.dataset.path);}
for(const el of [search,role,owner])el.addEventListener('input',filter);reset.addEventListener('click',()=>{search.value='';role.value='';owner.value='';filter();search.focus();});for(const li of files)li.querySelector('button').addEventListener('click',()=>selectFile(li,true));
if(mapSvg){const inspect=event=>{const group=event.target.closest('[data-node]');if(!group)return;const li=files.find(row=>'file:'+row.dataset.path===group.dataset.node);if(li&&!li.hidden)selectFile(li,true);};mapSvg.addEventListener('click',inspect);mapSvg.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){const group=event.target.closest('[data-node]');if(group){event.preventDefault();inspect(event);}}});}
document.addEventListener('keydown',event=>{if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&!event.target.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName)){event.preventDefault();search.focus();}});filter();selectFile(files.find(li=>li.dataset.roles.split(',').includes('changed'))||files[0]||null);
`;
